"""initial migration

Revision ID: 9dc432b0aa3c
Revises: 
Create Date: 2026-01-12 16:57:36.625959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc432b0aa3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Achievement',
    sa.Column('achievement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('source_information', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('项目参与者', '评审人', '秘书', '管理员', '企业支持者'), nullable=False),
    sa.Column('affiliation', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('user_profile', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('IncubationResource',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.Enum('生产合同', '技术支持', '供应链服务', '场地支持', '资金支持', '其他'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('开放中', '已关闭'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('Notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('redirect_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('Team',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('team_profile', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('Project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('maturity_level', sa.Enum('研发阶段', '小试阶段', '中试阶段', '小批量生产阶段'), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('待初审', '初审中', '复审中', '公示中', '已通过', '孵化中', '概念验证中', '孵化完成', '已取消'), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('UserInTeam',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('AchievementOfProject',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['Achievement.achievement_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('AuditRecord',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audit_type', sa.Enum('项目初审', '复审遴选', '经费审核'), nullable=False),
    sa.Column('result', sa.Enum('通过', '未通过'), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('Expenditure',
    sa.Column('expenditure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('expenditure_id')
    )
    op.create_table('FundRecord',
    sa.Column('fund_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_table('IncubationComment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['IncubationComment.comment_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('IncubationRecord',
    sa.Column('incubation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('planned_end_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('计划中', '进行中', '已完成', '已暂停'), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=True),
    sa.Column('incubation_plan', sa.Text(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('incubation_id')
    )
    op.create_table('Milestone',
    sa.Column('milestone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('未开始', '进行中', '已完成'), nullable=False),
    sa.Column('deliverable', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_table('ResourceApplication',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('待处理', '对接中', '已达成', '已拒绝'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['IncubationResource.resource_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('ReviewTask',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('assign_time', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('待确认', '进行中', '已完成'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('SupportIntention',
    sa.Column('intention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('support_type', sa.Enum('资金支持', '产业资源', '市场渠道', '其他'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('待处理', '已对接', '已婉拒'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('intention_id')
    )
    op.create_table('ProofOfConcept',
    sa.Column('poc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('incubation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_objective', sa.Text(), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('待开始', '进行中', '已完成', '已验证', '未通过'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('evidence_files', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incubation_id'], ['IncubationRecord.incubation_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('poc_id')
    )
    op.create_table('ReviewOpinion',
    sa.Column('opinion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('innovation_score', sa.SmallInteger(), nullable=True),
    sa.Column('potentiality_score', sa.SmallInteger(), nullable=True),
    sa.Column('feasibility_score', sa.SmallInteger(), nullable=True),
    sa.Column('teamwork_score', sa.SmallInteger(), nullable=True),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ReviewTask.task_id'], ),
    sa.PrimaryKeyConstraint('opinion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReviewOpinion')
    op.drop_table('ProofOfConcept')
    op.drop_table('SupportIntention')
    op.drop_table('ReviewTask')
    op.drop_table('ResourceApplication')
    op.drop_table('Milestone')
    op.drop_table('IncubationRecord')
    op.drop_table('IncubationComment')
    op.drop_table('FundRecord')
    op.drop_table('Expenditure')
    op.drop_table('AuditRecord')
    op.drop_table('AchievementOfProject')
    op.drop_table('UserInTeam')
    op.drop_table('Project')
    op.drop_table('Team')
    op.drop_table('Notification')
    op.drop_table('IncubationResource')
    op.drop_table('User')
    op.drop_table('Achievement')
    # ### end Alembic commands ###
