"""create resource tables

Revision ID: a1b2c3d4e5f6
Revises: e3028893d1b4
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e3028893d1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 IncubationResource 表
    op.create_table('IncubationResource',
    sa.Column('resource_id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.Enum('生产合同', '技术支持', '供应链服务', '场地支持', '资金支持', '其他', name='resource_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('开放中', '已关闭', name='resource_status'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    
    # 创建 ResourceApplication 表
    op.create_table('ResourceApplication',
    sa.Column('application_id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('待处理', '对接中', '已达成', '已拒绝', name='application_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['IncubationResource.resource_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ResourceApplication')
    op.drop_table('IncubationResource')
    # ### end Alembic commands ###
