"""create Milestone

Revision ID: e3028893d1b4
Revises: 
Create Date: 2026-01-11 02:10:27.270187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3028893d1b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 Milestone 表（如果不存在）
    op.create_table('Milestone',
    sa.Column('milestone_id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('未开始', '进行中', '已完成', name='milestone_status'), nullable=False, server_default='未开始'),
    sa.Column('deliverable', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('update_time', sa.DateTime(), nullable=True, onupdate=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['Project.project_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    
    # 修改 ReviewTask 表（如果存在 expert_id 索引则删除）
    # 注意：这里使用 try-except 包裹，因为表可能不存在或索引可能不存在
    try:
        op.drop_index('expert_id', table_name='ReviewTask')
    except:
        pass  # 索引不存在，忽略错误
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复 ReviewTask 表的索引
    try:
        op.create_index('expert_id', 'ReviewTask', ['reviewer_id'], unique=False)
    except:
        pass
    
    # 删除 Milestone 表
    op.drop_table('Milestone')
    # ### end Alembic commands ###
